name: travel_bus_app
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.5.4

dependencies:
  flutter:
    sdk: flutter

  get: ^4.6.6
  http: ^1.2.2
  flutter_dotenv: ^5.0.2
  intl: ^0.20.0
  connectivity_plus: ^6.1.0
  shared_preferences: ^2.3.2
  flutter_svg: ^2.0.14
  logger: ^2.5.0
  cupertino_icons: ^1.0.8
  flutter_screenutil: ^5.9.3
  json_annotation: ^4.9.0
  flutter_native_splash: ^2.2.11
  url_launcher: ^6.3.1
  otp_pin_field: ^1.3.1
  image_picker: ^1.1.2
  path_provider: ^2.1.5

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0
  build_runner: ^2.4.0
  json_serializable: ^6.7.0


flutter_native_splash:
  color: "#ffffff"          
  image: assets/icons/app_icon.png
  android: true
  ios: true
  android_gravity: center    
  ios_content_mode: center   

flutter:
  uses-material-design: true

  assets:
    - assets/icons/dark/
    - assets/icons/light/